"""Read working-tree files; never execute the target project's code or tools."""

import os
import re
import subprocess
from collections import Counter
from dataclasses import dataclass, field
from pathlib import Path

from pathspec import GitIgnoreSpec

from .languages import detect

ALWAYS_SKIP = frozenset(
    {".git", ".hg", ".svn", ".declank", "node_modules", ".venv", "venv", "__pycache__"}
)
VENDOR_DIRS = frozenset({"vendor", "vendors", "third_party", "third-party", "external"})
BUILD_DIRS = frozenset(
    {
        "dist",
        "build",
        "target",
        "coverage",
        ".next",
        ".nuxt",
        ".output",
        "generated",
        "__generated__",
        ".cache",
        ".turbo",
        ".pytest_cache",
        ".ruff_cache",
    }
)
TEST_DIRS = frozenset(
    {
        "test",
        "tests",
        "__tests__",
        "__mocks__",
        "fixtures",
        "__fixtures__",
        "e2e",
        "testdata",
        "test_data",
        "testing",
        "benches",
        "benchmarks",
    }
)
TEST_NAME = re.compile(
    r"(^(test|tests|fixture|fixtures)[._]|(_test|_spec|[.]test|[.]spec|[.]bench)[.]|Test[.]|Tests[.])"
)
GENERATED_NAME = re.compile(r"([.]min[.]|[.]generated[.]|[.]g[.]|[.]pb[.]|_pb2[.]|[.]d[.][cm]?ts$)")
GENERATED_HEADER = re.compile(
    rb"(?im)^\s*(?://|#|/\*|\*|--|;|<!--)\s*"
    rb"(?:@generated\b|code generated\b|auto[- ]generated\b|generated by\b|"
    rb"this (?:file|code) (?:is|was) (?:automatically )?generated\b)"
)


@dataclass
class ScanOptions:
    include_tests: bool = False
    include_vendor: bool = False
    include_generated: bool = False
    respect_gitignore: bool = True
    exclude: list[str] = field(default_factory=list)
    languages: set[str] = field(default_factory=set)
    mappings: dict[str, str] = field(default_factory=dict)
    max_bytes: int = 2 * 1024 * 1024
    functions: bool = False
    sql_dialect: str = "auto"


@dataclass
class Discovery:
    files: list[tuple[Path, str, str]] = field(default_factory=list)
    skipped: Counter = field(default_factory=Counter)
    issues: list[dict] = field(default_factory=list)
    method: str = "filesystem"


def exclusion_reason(relative: str, options: ScanOptions) -> str | None:
    path = Path(relative)
    dirs = set(path.parts[:-1])
    if dirs & ALWAYS_SKIP:
        return "dependencies-or-vcs"
    if not options.include_vendor and dirs & VENDOR_DIRS:
        return "vendor"
    if not options.include_generated and (dirs & BUILD_DIRS or GENERATED_NAME.search(path.name)):
        return "generated-or-build"
    if not options.include_tests and (dirs & TEST_DIRS or TEST_NAME.search(path.name)):
        return "tests-or-fixtures"
    return None


def _filesystem_paths(root: Path, options: ScanOptions, result: Discovery):
    specs: dict[Path, list[tuple[Path, GitIgnoreSpec]]] = {}

    def onerror(error: OSError):
        result.issues.append({"path": str(error.filename), "kind": "io", "message": str(error)})

    for directory, dirs, files in os.walk(root, followlinks=False, onerror=onerror):
        base = Path(directory)
        inherited = list(specs.get(base.parent, []))
        ignore = base / ".gitignore"
        if options.respect_gitignore and ignore.is_file():
            try:
                inherited.append((base, GitIgnoreSpec.from_lines(ignore.read_text().splitlines())))
            except (OSError, UnicodeError) as error:
                result.issues.append({"path": str(ignore), "kind": "io", "message": str(error)})
        specs[base] = inherited

        def ignored(path: Path, is_dir: bool, inherited=inherited) -> bool:
            matched = False
            for anchor, spec in inherited:
                checked = spec.check_file(
                    path.relative_to(anchor).as_posix() + ("/" if is_dir else "")
                )
                if checked.include is not None:
                    matched = bool(checked.include)
            return matched

        kept = []
        for name in sorted(dirs):
            path = base / name
            relative = path.relative_to(root).as_posix()
            reason = exclusion_reason(relative + "/_", options)
            if path.is_symlink():
                result.skipped["symlink-directories"] += 1
            elif reason:
                result.skipped[reason + "-directories"] += 1
            elif ignored(path, True):
                result.skipped["gitignored-directories"] += 1
            else:
                kept.append(name)
        dirs[:] = kept
        for name in sorted(files):
            path = base / name
            if ignored(path, False):
                result.skipped["gitignored"] += 1
            else:
                yield path


def discover(target: Path, options: ScanOptions) -> Discovery:
    result = Discovery()
    root = target if target.is_dir() else target.parent
    exclude = GitIgnoreSpec.from_lines(options.exclude)
    if target.is_file():
        paths = [target]
        result.method = "explicit-file"
    else:
        paths = None
        if options.respect_gitignore:
            try:
                command = subprocess.run(
                    [
                        "git",
                        "-C",
                        str(root),
                        "ls-files",
                        "--cached",
                        "--others",
                        "--exclude-standard",
                        "--deduplicate",
                        "-z",
                        "--",
                        ".",
                    ],
                    capture_output=True,
                    check=False,
                    timeout=60,
                )
                if command.returncode == 0:
                    paths = [root / os.fsdecode(p) for p in command.stdout.split(b"\0") if p]
                    result.method = "git-working-tree"
            except (OSError, subprocess.TimeoutExpired):
                pass
        if paths is None:
            paths = _filesystem_paths(root, options, result)
    for path in paths:
        relative = path.relative_to(root).as_posix()
        reason = exclusion_reason(relative, options)
        if reason:
            result.skipped[reason] += 1
        elif exclude.match_file(relative):
            result.skipped["user-excluded"] += 1
        elif path.is_symlink():
            result.skipped["symlink"] += 1
        elif not path.exists():
            result.skipped["deleted"] += 1
        elif not path.is_file():
            result.skipped["non-file-or-submodule"] += 1
        else:
            language = detect(path, options.mappings)
            if language is None:
                result.skipped["unsupported-extension"] += 1
            elif options.languages and language not in options.languages:
                result.skipped["language-filter"] += 1
            else:
                result.files.append((path, relative, language))
    result.files.sort(key=lambda row: row[1])
    return result
