import subprocess
from pathlib import Path

from declank.discovery import ScanOptions, discover
from declank.scanner import analyze, scan


def put(root: Path, name: str, content="x = 1\n") -> Path:
    path = root / name
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    return path


def paths(root, options=None):
    return {row[1] for row in discover(root, options or ScanOptions()).files}


def test_defaults_and_explicit_inclusions(tmp_path):
    for name in [
        "a.py",
        "test_a.py",
        "a_test.go",
        "src/fixture.ts",
        "vendor/b.py",
        "tests/c.py",
        "dist/d.py",
        "node_modules/e.py",
        ".venv/f.py",
        "types.d.ts",
    ]:
        put(tmp_path, name)
    assert paths(tmp_path) == {"a.py"}
    assert paths(
        tmp_path,
        ScanOptions(
            include_tests=True,
            include_generated=True,
            include_vendor=True,
        ),
    ) == {
        "a.py",
        "test_a.py",
        "a_test.go",
        "src/fixture.ts",
        "vendor/b.py",
        "tests/c.py",
        "dist/d.py",
        "types.d.ts",
    }


def test_nested_gitignore_and_negation_without_git(tmp_path):
    put(tmp_path, ".gitignore", "*.py\n!keep.py\n")
    put(tmp_path, "sub/.gitignore", "!local.py\n")
    for name in ["keep.py", "drop.py", "sub/local.py", "sub/other.py"]:
        put(tmp_path, name)
    assert paths(tmp_path) == {"keep.py", "sub/local.py"}
    assert len(paths(tmp_path, ScanOptions(respect_gitignore=False))) == 4


def test_git_discovery_includes_dirty_and_untracked_but_not_ignored(tmp_path):
    subprocess.run(["git", "init", "-q", str(tmp_path)], check=True)
    put(tmp_path, ".gitignore", "ignored.py\n")
    put(tmp_path, "tracked.py", "a = 1\n")
    put(tmp_path, "deleted.py")
    subprocess.run(["git", "-C", str(tmp_path), "add", "."], check=True)
    put(tmp_path, "tracked.py", "a = 1 + 2\n")
    put(tmp_path, "new.py")
    put(tmp_path, "ignored.py")
    (tmp_path / "deleted.py").unlink()
    result = discover(tmp_path, ScanOptions())
    assert result.method == "git-working-tree"
    assert {row[1] for row in result.files} == {"tracked.py", "new.py"}
    assert result.skipped["deleted"] == 1
    report = scan(tmp_path)
    assert next(r for r in report["records"] if r["path"] == "tracked.py")["total_operands"] == 3


def test_git_subdirectory_paths_are_relative_to_scan_root(tmp_path):
    subprocess.run(["git", "init", "-q", str(tmp_path)], check=True)
    put(tmp_path, "outside.py")
    put(tmp_path, "sub/inside.py")
    assert paths(tmp_path / "sub") == {"inside.py"}


def test_symlinks_are_not_followed(tmp_path):
    put(tmp_path, "a.py")
    (tmp_path / "link.py").symlink_to(tmp_path / "a.py")
    (tmp_path / "loop").symlink_to(tmp_path, target_is_directory=True)
    assert paths(tmp_path) == {"a.py"}


def test_extensions_can_be_overridden_and_filtered(tmp_path):
    put(tmp_path, "a.custom")
    put(tmp_path, "b.py")
    result = discover(tmp_path, ScanOptions(mappings={".custom": "ruby"}, languages={"ruby"}))
    assert [(row[1], row[2]) for row in result.files] == [("a.custom", "ruby")]


def test_user_exclusion_applies_in_subdirectories(tmp_path):
    put(tmp_path, "a.py")
    put(tmp_path, "sub/a.py")
    put(tmp_path, "sub/keep.py")
    assert paths(tmp_path, ScanOptions(exclude=["a.py"])) == {"sub/keep.py"}


def test_generated_headers_and_minified_artifacts_are_excluded(tmp_path):
    put(tmp_path, "generated.py", "# Code generated by a tool. DO NOT EDIT.\nx = 1\n")
    put(tmp_path, "bundle.js", "const s='" + "x" * 6000 + "';")
    put(tmp_path, "normal.py", 's = "This file is generated"\n')
    report = scan(tmp_path)
    assert [r["path"] for r in report["records"]] == ["normal.py"]
    assert report["summary"]["skipped"]["minified-heuristic"] == 1
    assert len(scan(tmp_path, ScanOptions(include_generated=True))["records"]) == 3


def test_inline_rust_tests_are_excluded_unless_requested():
    source = b"fn keep() {}\n#[cfg(test)]\nmod tests { #[test] fn foo(){ let x=1+2; } }\n"
    production, _ = analyze(source, "rust", "a.rs")
    all_code, _ = analyze(source, "rust", "a.rs", include_tests=True)
    functions, _ = analyze(source, "rust", "a.rs", functions=True)
    assert production[0]["sloc"] == 1
    assert production[0]["length"] < all_code[0]["length"]
    assert [row["name"] for row in functions] == ["keep"]


def test_errors_are_visible_and_bad_files_are_not_ranked(tmp_path):
    put(tmp_path, "good.py")
    put(tmp_path, "bad.py", "def broken(")
    put(tmp_path, "huge.py", "#" * 500)
    (tmp_path / "binary.py").write_bytes(b"\0\xff")
    report = scan(tmp_path, ScanOptions(max_bytes=100))
    assert [row["path"] for row in report["records"]] == ["good.py"]
    assert not report["complete"]
    assert {issue["kind"] for issue in report["issues"]} == {"parse", "size", "read-or-parser"}


def test_source_fingerprint_changes_with_working_tree_content(tmp_path):
    put(tmp_path, "a.py")
    first = scan(tmp_path)["source_fingerprint"]
    assert first == scan(tmp_path)["source_fingerprint"]
    put(tmp_path, "a.py", "x = 1 + 2\n")
    assert first != scan(tmp_path)["source_fingerprint"]
