import hashlib
import os
from pathlib import Path

import pytest

from walleye.discovery import ScanOptions
from walleye.scanner import scan


def _stable_report(report):
    return {
        key: value for key, value in report.items() if key not in {"scanned_at", "duration_seconds"}
    }


def _assert_scan_error(path: Path, expected: str) -> None:
    with pytest.raises(ValueError) as error:
        scan(path)
    assert str(error.value) == expected


def test_scan_preserves_file_outcomes_and_report_aggregates(tmp_path):
    valid = b"def add(value):\n    return value + 1\n"
    sources = {
        "binary.py": b"\0\xff",
        "generated.py": b"# Code generated by a tool. DO NOT EDIT.\nx = 1\n",
        "malformed.py": b"def broken(\n",
        "oversized.py": b"x" * 101,
        "valid.py": valid,
    }
    for name, source in sources.items():
        (tmp_path / name).write_bytes(source)

    options = ScanOptions(max_bytes=100, functions=True, respect_gitignore=False)
    first_snapshot = {}
    first = scan(tmp_path, options, source_snapshot=first_snapshot)
    second_snapshot = {}
    second = scan(tmp_path, options, source_snapshot=second_snapshot)

    assert _stable_report(first) == _stable_report(second)
    assert first["complete"] is False
    assert first["source_hashes"] == {
        "valid.py": hashlib.sha256(valid).hexdigest(),
    }
    assert first_snapshot == second_snapshot == {"valid.py": valid}
    assert first["source_fingerprint"] == second["source_fingerprint"]
    assert len(first["source_fingerprint"]) == 64

    summary = first["summary"]
    assert summary["candidate_files"] == 5
    assert summary["scanned_files"] == 1
    assert summary["records"] == 1
    assert summary["file_records"] == 1
    assert summary["function_records"] == 1
    assert summary["top_level_functions"] == 1
    assert summary["nested_functions"] == 0
    assert summary["languages"] == {"python": 1}
    assert summary["parsers"] == {"tree-sitter": 1}
    assert summary["skipped"] == {
        "generated-header": 1,
        "oversized": 1,
        "parse-error": 1,
        "read-or-parser-error": 1,
    }
    assert summary["issue_count"] == len(first["issues"])

    assert {(issue["path"], issue["kind"]) for issue in first["issues"]} == {
        ("binary.py", "read-or-parser"),
        ("malformed.py", "parse"),
        ("oversized.py", "size"),
    }
    assert next(issue for issue in first["issues"] if issue["kind"] == "size") == {
        "path": "oversized.py",
        "kind": "size",
        "message": "Exceeds --max-bytes",
    }
    assert next(issue for issue in first["issues"] if issue["kind"] == "read-or-parser") == {
        "path": "binary.py",
        "kind": "read-or-parser",
        "line": 1,
        "column": 1,
        "message": "Binary content (NUL byte); file left unscored",
    }

    coverage = first["coverage"]
    assert coverage["candidate_files"] == 5
    assert coverage["parsed_files"] == 1
    assert coverage["scanned_files"] == 1
    assert coverage["file_parse_share"] == 0.2
    assert coverage["files_with_functions"] == 1
    assert coverage["recognized_functions"] == 1
    assert coverage["nested_functions"] == 0
    assert coverage["top_level_functions"] == 1
    assert coverage["complexity_by_function_status"] == {"supported": 1}
    assert coverage["languages"] == {"python": 1}

    assert [(row["path"], row["name"]) for row in first["records"]] == [
        ("valid.py", "add"),
    ]
    graph = first["callgraph"]
    assert graph["edges"] == []
    assert graph["unresolved"] == []
    assert graph["coverage"]["functions_analyzed"] == 1
    assert graph["coverage"]["call_sites"] == 0
    assert [(node["path"], node["name"], node["line"]) for node in graph["nodes"]] == [
        ("valid.py", "add", 1)
    ]

    scores = first["scores"]
    assert scores["profile"] == "declank-quality-v1"
    assert scores["overall_score"] is not None
    assert scores["maintainability_index"] is not None
    assert scores["complexity_score"] is not None
    assert scores["coverage"]["complexity_units"] == 1
    assert scores["coverage"]["maintainability_units"] == 1
    assert scores["by_language"]["python"]["files"] == 1
    assert "health" in first
    assert first["health"] == second["health"]


def test_scan_rejects_missing_target(tmp_path):
    missing = tmp_path / "missing.py"
    _assert_scan_error(
        missing,
        f"Path does not exist: {missing.expanduser().absolute()}",
    )


def test_scan_rejects_symlink_target(tmp_path):
    real_file = tmp_path / "real.py"
    real_file.write_text("x = 1\n")
    link = tmp_path / "link.py"
    link.symlink_to(real_file)

    _assert_scan_error(link, "Scan a real file or directory, not a symbolic link")


@pytest.mark.skipif(
    not hasattr(os, "mkfifo"),
    reason="FIFO targets are unavailable",
)
def test_scan_rejects_fifo_target(tmp_path):
    fifo = tmp_path / "pipe.py"
    os.mkfifo(fifo)
    try:
        _assert_scan_error(
            fifo,
            f"Not a regular file or directory: {fifo.expanduser().absolute()}",
        )
    finally:
        fifo.unlink()
