[package]
name = "walleye-node"
version.workspace = true
edition.workspace = true

[dependencies]
walleye-typesafe = { path = "../walleye-typesafe" }
rustls.workspace = true
tokio-tungstenite.workspace = true
walleye-v8 = { path = "../walleye-v8" }
async-trait.workspace = true
walleye-cache.workspace = true
walleye-lance.workspace = true
walleye-bitr.workspace = true
arrow-array.workspace = true
arrow-schema.workspace = true
arrow-json = "58"
arrow-ipc.workspace = true
arrow-row = "58"
xxhash-rust.workspace = true
lance-io = { version = "=11.0.0", default-features = false, features = ["aws"] }
object_store = "=0.13.2"
futures.workspace = true
base64 = "0.22.1"
hmac.workspace = true
sha2.workspace = true
walleye-ring.workspace = true
walleye-bitr-server.workspace = true
axum.workspace = true
reqwest.workspace = true
bytes.workspace = true
hex.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
uuid.workspace = true
lance-core = "=11.0.0"

[dev-dependencies]
walleye-bitr-server = { path = "../walleye-bitr-server" }
walleye-bitr.workspace = true
base64 = "0.22.1"
hmac.workspace = true
sha2.workspace = true
hex.workspace = true
object_store_bitr = { package = "object_store", version = "0.14.0" }
futures.workspace = true
tokio-tungstenite.workspace = true
tempfile.workspace = true
tower.workspace = true
arrow-ipc.workspace = true

[lints]
workspace = true
