apiVersion: v1
kind: ServiceAccount
metadata:
  name: walleye-cache
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: walleye-cache-discovery
rules:
  - apiGroups: [discovery.k8s.io]
    resources: [endpointslices]
    verbs: [list]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: walleye-cache-discovery
subjects:
  - kind: ServiceAccount
    name: walleye-cache
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: walleye-cache-discovery
